### ISSUE TITLE
Misleading configuration example

### ISSUE THREAD

**Issue by imatrixcz** [Cmajda/ha_cez_distribuce#2]
There should be name of the region without commas - "stred" not "střed"

Fixed version:

# Příklad záznamu v configuration.yaml pro zobrazení aktuálního stavu HDO
binary_sensor:
  - platform: cez_hdo
    region: stred
    code: 405

sensor:
  - platform: cez_hdo
    region: stred
    code: 405

**Comment by Cmajda** [comment]
Fixed [commit](https://github.com/Cmajda/ha_cez_distribuce/commit/67dc5bb60a9105def7f8236f95c90339736cbd45)

**Comment by Cmajda** [comment]
Thanks for the feedback :handshake:
